import type { Metadata } from "next";
import Link from "next/link";
import { FAQAccordion } from "@/components/FAQAccordion";
import { FinalCTA } from "@/components/FinalCTA";
import RelatedPages from "@/components/RelatedPages";
import { ListingOutputShowcase } from "@/components/ListingOutputShowcase";
import { QuickAnswer } from "@/components/QuickAnswer";
import { Button } from "@/components/Button";
import { Check, ArrowRight } from "lucide-react";
import { ContextualCTA } from "@/components/ContextualCTA";
import { AuthorByline } from "@/components/AuthorByline";

export const metadata: Metadata = {
  title: "DPI vs Pixel Dimensions: Why 300 DPI Isn't Enough",
  description:
    "DPI alone doesn't decide print quality — pixel dimensions do. Learn why a 300 DPI file can still print blurry and how to check if yours is print-ready.",
  alternates: { canonical: "https://snaptosize.com/dpi-vs-pixel-dimensions" },
  openGraph: {
    title: "DPI vs Pixel Dimensions: Why 300 DPI Isn't Enough | SnapToSize",
    description:
      "DPI is just a label — pixel dimensions are the real data. Here's why a 300 DPI file can still print blurry, and how to check your file is actually print-ready.",
    url: "https://snaptosize.com/dpi-vs-pixel-dimensions",
    modifiedTime: "2026-05-28T00:00:00Z",
    // TODO: og image generated by og-screenshot step
    images: [
      {
        url: "/assets/og/dpi-vs-pixel-dimensions.png",
        width: 1200,
        height: 630,
        alt: "DPI vs Pixel Dimensions — why 300 DPI alone doesn't guarantee a sharp print",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "DPI vs Pixel Dimensions: Why 300 DPI Isn't Enough",
    description:
      "DPI is a label, pixels are the data. Why a 300 DPI file can still print blurry — and how to check yours.",
    images: ["/assets/og/dpi-vs-pixel-dimensions.png"],
  },
};

export default function DpiVsPixelDimensionsPage() {
  const CTA_URL =
    "https://app.snaptosize.com?source=seo_dpi-vs-pixel-dimensions&kind=guide";

  const articleJsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: "DPI vs Pixel Dimensions: What Actually Decides Print Quality",
    description:
      "DPI is a printing instruction, not a measure of detail. Pixel dimensions decide whether a print is sharp. Why a 300 DPI file can still print blurry, and how to check your file.",
    url: "https://snaptosize.com/dpi-vs-pixel-dimensions",
    datePublished: "2026-05-27",
    dateModified: "2026-05-27",
    author: {
      "@type": "Organization",
      name: "SnapToSize",
      url: "https://snaptosize.com",
    },
  };

  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: "https://snaptosize.com",
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Etsy Print Sizes",
        item: "https://snaptosize.com/etsy-print-sizes",
      },
      {
        "@type": "ListItem",
        position: 3,
        name: "DPI vs Pixel Dimensions",
        item: "https://snaptosize.com/dpi-vs-pixel-dimensions",
      },
    ],
  };

  const faqs = [
    {
      q: "Does 300 DPI mean high resolution?",
      a: "Not by itself. 300 DPI is just a printing instruction — it tells the printer how tightly to pack pixels, but it doesn't say how many pixels the file has. A tiny image can be tagged ‘300 DPI’ and still be low resolution. Real resolution lives in the pixel dimensions.",
    },
    {
      q: "Is DPI the same as resolution?",
      a: "No. Resolution is the total pixel count (e.g. 2400×3000). DPI is how densely those pixels print onto paper. Two files can both say ‘300 DPI’ yet have wildly different resolutions — only the pixel dimensions tell you how much detail you actually have.",
    },
    {
      q: "Can I just change the DPI to make a low-res file print-ready?",
      a: "No — this is the single most common mistake. Bumping the DPI number in Photoshop or Preview only edits a label; it adds zero new detail. If the pixels aren't there, the print stays blurry. You need a source with enough actual pixel dimensions for the print size.",
    },
    {
      q: "What pixel dimensions do I need for an 8×10 print at 300 DPI?",
      a: "2400×3000 pixels (8×300 by 10×300). Anything smaller will look soft when printed at 8×10, no matter what DPI value the file claims. See the full per-size chart on our Print Sizes at 300 DPI page.",
    },
    {
      q: "How do I check my image's pixel dimensions?",
      a: "Right-click the file and open Properties (Windows) or Get Info (Mac), or check the image-size dialog in any editor. Read the width × height in pixels — ignore the DPI field. Compare that to inches × 300 for your target size to know if it's print-ready.",
    },
    {
      q: "Why does my 300 DPI file still look blurry when printed?",
      a: "Because its pixel dimensions are too low for the size you're printing. When a small file is stretched across a larger print, the effective DPI drops far below 300 and detail breaks down. For the step-by-step export fix, see our guide on fixing blurry Etsy prints.",
    },
  ];

  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  const formulaRows = [
    { size: "5×7", w: 1500, h: 2100 },
    { size: "8×10", w: 2400, h: 3000 },
    { size: "16×20", w: 4800, h: 6000 },
  ];

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />

      <AuthorByline lastUpdated="May 28, 2026" />

      {/* ===== HERO — full-bleed, "tag vs data" pixel-grid contrast motif ===== */}
      <section
        className="relative overflow-hidden border-b border-border"
        style={{
          background:
            "radial-gradient(120% 140% at 80% 0%, #0b1f1d 0%, #080d0d 55%, #060909 100%)",
        }}
      >
        {/* faint baseline grid */}
        <div
          aria-hidden
          className="absolute inset-0 opacity-[0.5]"
          style={{
            backgroundImage:
              "linear-gradient(rgba(45,212,191,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(45,212,191,0.04) 1px, transparent 1px)",
            backgroundSize: "44px 44px",
          }}
        />
        {/* corner glow blobs */}
        <div
          aria-hidden
          className="absolute -top-24 -right-24 h-[420px] w-[420px] rounded-full blur-3xl"
          style={{ background: "radial-gradient(circle, rgba(45,212,191,0.16), transparent 70%)" }}
        />
        <div
          aria-hidden
          className="absolute -bottom-32 -left-24 h-[360px] w-[360px] rounded-full blur-3xl"
          style={{ background: "radial-gradient(circle, rgba(167,139,250,0.12), transparent 70%)" }}
        />

        <div className="container mx-auto px-4 md:px-8 max-w-[1200px] relative z-10 pt-10 pb-16 md:pt-14 md:pb-24">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            {/* ── Left: text ── */}
            <div className="max-w-[620px]">
              <nav className="mb-5 flex items-center gap-1.5 text-xs text-foreground-60/60">
                <Link href="/" className="hover:text-foreground transition-colors">Home</Link>
                <span>/</span>
                <Link href="/etsy-print-sizes" className="hover:text-foreground transition-colors">Etsy Print Sizes</Link>
                <span>/</span>
                <span className="text-foreground-60">DPI vs Pixel Dimensions</span>
              </nav>

              <p className="mb-4 flex items-center gap-3 text-xs font-mono font-semibold uppercase tracking-[0.18em]" style={{ color: "#2DD4BF" }}>
                <span className="inline-block h-px w-8" style={{ background: "#2DD4BF" }} />
                Resolution Concept
              </p>

              <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-3 leading-[1.08]">
                DPI vs Pixel Dimensions
              </h1>
              <p className="text-xl md:text-2xl font-medium text-foreground-60 mb-6 leading-[1.15]">
                What actually decides print quality
              </p>

              <p className="text-lg text-foreground-60 mb-8">
                A file tagged <strong className="text-foreground">300 DPI</strong> can still print blurry. DPI is a label the printer reads; the real detail lives in your <strong className="text-foreground">pixel dimensions</strong>. Here&apos;s the difference — and how to check if your file is truly print-ready.
              </p>

              <a href={CTA_URL} target="_blank" rel="noopener noreferrer" className="inline-block mb-7">
                <Button className="text-sm px-6 py-2.5">
                  Generate Sizes Instantly
                  <ArrowRight className="ml-2 h-4 w-4 inline" />
                </Button>
              </a>

              <div className="flex flex-wrap gap-2">
                {["Pixels = real detail", "DPI = just a label", "True 300 DPI exports"].map((pill) => (
                  <span
                    key={pill}
                    className="inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-medium backdrop-blur"
                    style={{
                      border: "1px solid rgba(45,212,191,0.3)",
                      background: "rgba(45,212,191,0.08)",
                      color: "#2DD4BF",
                    }}
                  >
                    <Check className="h-3 w-3" />
                    {pill}
                  </span>
                ))}
              </div>
            </div>

            {/* ── Right: tag-vs-data contrast visual (CSS only) ── */}
            <div className="hidden lg:block">
              <div className="relative">
                {/* shared "300 DPI" tag floating over both */}
                <div
                  className="absolute left-1/2 -translate-x-1/2 -top-4 z-20 rounded-full px-4 py-1.5 font-mono text-xs font-semibold"
                  style={{
                    background: "rgba(8,13,13,0.9)",
                    border: "1px solid rgba(45,212,191,0.45)",
                    color: "#2DD4BF",
                    boxShadow: "0 0 30px rgba(45,212,191,0.15)",
                  }}
                >
                  Both tagged &ldquo;300 DPI&rdquo;
                </div>

                <div className="grid grid-cols-2 gap-4 pt-6">
                  {/* Low-res: chunky pixel grid */}
                  <div
                    className="rounded-2xl p-4"
                    style={{
                      background: "linear-gradient(160deg, #1a1212 0%, #0c0808 100%)",
                      border: "1px solid rgba(248,113,113,0.25)",
                    }}
                  >
                    <div
                      className="aspect-square rounded-lg overflow-hidden mb-3"
                      style={{
                        backgroundImage:
                          "linear-gradient(135deg, #7c3a4a 0%, #b06a52 45%, #d8b074 100%)",
                        backgroundSize: "cover",
                        imageRendering: "pixelated",
                        filter: "blur(1.5px) contrast(0.92)",
                        boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.04)",
                      }}
                    >
                      <div
                        className="h-full w-full"
                        style={{
                          backgroundImage:
                            "linear-gradient(rgba(0,0,0,0.18) 1px, transparent 1px), linear-gradient(90deg, rgba(0,0,0,0.18) 1px, transparent 1px)",
                          backgroundSize: "20px 20px",
                        }}
                      />
                    </div>
                    <p className="font-mono text-[11px] mb-0.5" style={{ color: "rgba(248,113,113,0.85)" }}>
                      600×750 px
                    </p>
                    <p className="text-[11px] text-foreground-60">Stretched to 8×10 → ~75 DPI → blurry</p>
                  </div>

                  {/* High-res: fine smooth grid */}
                  <div
                    className="rounded-2xl p-4"
                    style={{
                      background: "linear-gradient(160deg, #0a1f1e 0%, #061210 100%)",
                      border: "1px solid rgba(45,212,191,0.3)",
                      boxShadow: "0 0 40px rgba(45,212,191,0.06)",
                    }}
                  >
                    <div
                      className="aspect-square rounded-lg overflow-hidden mb-3"
                      style={{
                        backgroundImage:
                          "linear-gradient(135deg, #7c3a4a 0%, #b06a52 45%, #d8b074 100%)",
                        backgroundSize: "cover",
                        boxShadow: "inset 0 0 0 1px rgba(45,212,191,0.12)",
                      }}
                    >
                      <div
                        className="h-full w-full"
                        style={{
                          backgroundImage:
                            "linear-gradient(rgba(0,0,0,0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(0,0,0,0.06) 1px, transparent 1px)",
                          backgroundSize: "5px 5px",
                        }}
                      />
                    </div>
                    <p className="font-mono text-[11px] mb-0.5" style={{ color: "#2DD4BF" }}>
                      2400×3000 px
                    </p>
                    <p className="text-[11px] text-foreground-60">True 8×10 at 300 DPI → sharp</p>
                  </div>
                </div>

                <p className="mt-4 text-center font-mono text-[11px]" style={{ color: "rgba(255,255,255,0.3)" }}>
                  Same DPI tag. Very different pixels.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ===== CONTENT ===== */}
      <div className="container mx-auto px-4 md:px-8 max-w-[1200px] py-12">
        {/* QuickAnswer — FIRST content element (featured-snippet target) */}
        <QuickAnswer question="Does 300 DPI mean high resolution?">
          <p>
            Not by itself. <strong>DPI is a printing instruction</strong> — it tells the printer how tightly to pack the pixels it&apos;s given. It says nothing about how many pixels the file actually contains. The real resolution lives in the <strong>pixel dimensions</strong> (e.g. 2400×3000). A small file can be tagged &ldquo;300 DPI&rdquo; and still print blurry, because changing the DPI number never adds detail that wasn&apos;t there.
          </p>
        </QuickAnswer>

        {/* SECTION 1 — What DPI actually is */}
        <section className="mt-16 mb-16">
          <h2 className="text-2xl md:text-3xl font-bold mb-4">
            What DPI Actually Is (and Isn&apos;t)
          </h2>
          <p className="text-foreground-60 mb-4">
            DPI stands for <em>dots per inch</em> — a small piece of metadata that tells the printer how densely to lay down the pixels you give it. That&apos;s the whole job: a packing instruction. It is <strong className="text-foreground">not</strong> a measure of how much detail your image contains.
          </p>
          <p className="text-foreground-60 mb-4">
            This is where most sellers get burned. Opening a low-res file in Photoshop or Preview and typing &ldquo;300&rdquo; into the DPI field feels like an upgrade — but it changes a label, not the data. The pixel count stays exactly the same. You haven&apos;t added a single dot of detail; you&apos;ve just told the printer to squeeze the same pixels into a smaller area.
          </p>
          <p className="text-foreground-60">
            DPI only becomes meaningful when it&apos;s tied to a physical print size. On its own, &ldquo;300 DPI&rdquo; is a setting, not a guarantee. To see how DPI maps to real pixel targets across every size, the{" "}
            <Link href="/print-sizes-at-300-dpi" className="text-accent underline hover:no-underline">
              print sizes at 300 DPI chart
            </Link>{" "}
            lays it out completely.
          </p>
        </section>

        {/* SECTION 2 — What pixel dimensions actually are */}
        <section className="mb-16">
          <h2 className="text-2xl md:text-3xl font-bold mb-4">
            What Pixel Dimensions Actually Are
          </h2>
          <p className="text-foreground-60 mb-4">
            Pixel dimensions — like <strong className="text-foreground">2400×3000</strong> — are the real data. They&apos;re the actual count of pixels that make up your image, and they set the hard ceiling on how much detail can ever appear in the print. More pixels means more printable detail. Fewer pixels means there&apos;s simply less information to work with, no matter how you label it.
          </p>
          <p className="text-foreground-60 mb-4">
            Think of it this way: <strong className="text-foreground">pixels are the paint you have; DPI is how thinly you spread it across the wall.</strong> A small bucket of paint (few pixels) spread across a large wall (big print) goes thin and patchy. The same paint on a small wall stays rich and solid. DPI is just the spreading rate — it can&apos;t conjure more paint.
          </p>
          <p className="text-foreground-60">
            So when you&apos;re choosing a target size, you&apos;re really asking: do I have enough pixels to fill it at a high spreading density? Pixel dimensions are the substance. DPI is the label. For the resolution numbers that actually matter when prepping printables, see{" "}
            <Link href="/best-resolution-for-etsy-printables" className="text-accent underline hover:no-underline">
              the best resolution for Etsy printables
            </Link>
            .
          </p>
        </section>

        {/* SECTION 3 — Why a 300 DPI file can still print blurry */}
        <section className="mb-16">
          <h2 className="text-2xl md:text-3xl font-bold mb-4">
            Why a 300 DPI File Can Still Print Blurry
          </h2>
          <p className="text-foreground-60 mb-4">
            This is the crux of the confusion. Sellers regularly report being &ldquo;confused why the image printed blurry despite being 300 DPI&rdquo; — and buyers occasionally receive a large print, like an A1, that arrives at &ldquo;terribly low resolution.&rdquo; The DPI tag said 300. The print still looked soft. How?
          </p>
          <p className="text-foreground-60 mb-4">
            The mechanism is simple once you separate the tag from the data. Say you have a 600×750 px file tagged &ldquo;300 DPI.&rdquo; At a true 300 DPI, that file only fills a <strong className="text-foreground">2×2.5 inch</strong> print (600÷300 by 750÷300). Stretch those same 600×750 pixels across an <strong className="text-foreground">8×10</strong> print and the printer is now spreading them at roughly <strong className="text-foreground">75 effective DPI</strong> — far below the 300 it claims. Every pixel gets blown up four times wider, and the result is blur.
          </p>
          <p className="text-foreground-60">
            The DPI tag never lied about its job — it just couldn&apos;t create pixels that weren&apos;t there. This page explains the <em>why</em>. For the step-by-step export fix when a print comes back soft, hand off to our guide on{" "}
            <Link href="/etsy-digital-download-blurry-prints" className="text-accent underline hover:no-underline">
              fixing blurry Etsy digital download prints
            </Link>
            .
          </p>
        </section>

        {/* CTA 1 — after the concept lands, before the formula */}
        <div className="mb-16">
          <ContextualCTA
            problem="Working out whether your pixels are enough for every Etsy size — then exporting each one at a true 300 DPI — is tedious and easy to get wrong."
            solution="SnapToSize outputs the exact pixel dimensions at a true 300 DPI for up to 70 sizes from one upload — no manual math, no guessing whether the DPI tag is honest."
            appUrl={CTA_URL}
            buttonText="Generate Sizes Instantly"
          />
        </div>

        {/* SECTION 4 — The formula + small table */}
        <section className="mb-16">
          <h2 className="text-2xl md:text-3xl font-bold mb-4">
            The Formula: Inches × 300 = Required Pixels
          </h2>
          <p className="text-foreground-60 mb-6">
            Here&apos;s the one piece of math that resolves the whole confusion. To know the minimum pixels you need, multiply each side of the print in inches by 300:
          </p>
          <div className="rounded-xl border border-border bg-muted/20 p-5 mb-6 text-center">
            <p className="font-mono text-base md:text-lg text-foreground">
              width<span className="text-foreground-60">(in)</span> × 300{" "}
              <span className="text-accent">and</span> height<span className="text-foreground-60">(in)</span> × 300{" "}
              <span className="text-accent">=</span> minimum pixel dimensions
            </p>
          </div>
          <div className="overflow-x-auto rounded-xl border border-border mb-4">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border bg-muted/50">
                  <th className="px-4 py-3 text-left font-semibold text-foreground-60">Print size (inches)</th>
                  <th className="px-4 py-3 text-left font-semibold text-foreground-60">Math</th>
                  <th className="px-4 py-3 text-left font-semibold text-foreground-60">Required pixels at 300 DPI</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {formulaRows.map((row) => (
                  <tr key={row.size} className="hover:bg-muted/30 transition-colors">
                    <td className="px-4 py-3 font-medium">{row.size}&quot;</td>
                    <td className="px-4 py-3 font-mono text-foreground-60 text-xs">
                      {row.size.split("×")[0]}×300 by {row.size.split("×")[1]}×300
                    </td>
                    <td className="px-4 py-3 font-mono text-accent">
                      {row.w.toLocaleString()}×{row.h.toLocaleString()} px
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="text-foreground-60 text-sm">
            This is <strong className="text-foreground">not</strong> the full chart — just three examples to show the pattern. For every Etsy size&apos;s exact pixels, see the{" "}
            <Link href="/print-sizes-at-300-dpi" className="text-accent underline hover:no-underline">
              complete 300 DPI pixel chart
            </Link>
            . The 8×10 row above is the most-sold size — there&apos;s a dedicated{" "}
            <Link href="/etsy-8x10-print-size" className="text-accent underline hover:no-underline">
              8×10 print size guide
            </Link>{" "}
            with buyer framing tips. (Pixels also have to land on the right{" "}
            <Link href="/etsy-print-ratios" className="text-accent underline hover:no-underline">
              print ratio
            </Link>{" "}
            for the size you&apos;re targeting.)
          </p>
        </section>

        {/* Mid-page CTA — after formula "aha" moment */}
        <div className="mb-16 rounded-2xl border border-teal-500/30 bg-teal-500/5 p-6 md:p-8 flex flex-col md:flex-row items-start md:items-center gap-6">
          <div className="flex-1">
            <p className="text-xs font-semibold uppercase tracking-widest text-teal-400 mb-2">Skip the math</p>
            <p className="text-lg md:text-xl font-bold text-foreground mb-1">
              SnapToSize runs this formula for every Etsy size automatically.
            </p>
            <p className="text-sm text-foreground-60">
              Upload once → exact pixel dimensions for all ratios at true 300 DPI. No spreadsheet, no guessing.
            </p>
          </div>
          <Link
            href={CTA_URL}
            className="gradient-btn shrink-0 whitespace-nowrap"
          >
            Try it free →
          </Link>
        </div>

        {/* SECTION 5 — How to check your file's real resolution */}
        <section className="mb-16">
          <h2 className="text-2xl md:text-3xl font-bold mb-4">
            How to Check Your File&apos;s Real Resolution
          </h2>
          <p className="text-foreground-60 mb-4">
            The trick is to <strong className="text-foreground">ignore the DPI field entirely</strong> and read the true pixel dimensions instead. On Windows, right-click the file and open <em>Properties → Details</em>. On Mac, right-click and choose <em>Get Info</em>. Or open the image-size dialog in any editor — Photoshop, Preview, GIMP, Affinity — and read the width × height <em>in pixels</em>.
          </p>
          <p className="text-foreground-60 mb-4">
            Then compare that number against the formula. If your file is 2400×3000 px, it&apos;s genuinely print-ready for 8×10. If it&apos;s 600×750 px, no DPI setting will save it — the pixels just aren&apos;t there, and you&apos;ll need a higher-resolution source instead.
          </p>
          <p className="text-foreground-60">
            That&apos;s the whole check: <strong className="text-foreground">actual pixels vs. required pixels.</strong> If actual is equal to or greater than required, you&apos;re good. If it&apos;s lower, the DPI tag is writing a cheque the file can&apos;t cash. For a full breakdown of the resolution numbers to aim for, see{" "}
            <Link href="/best-resolution-for-etsy-printables" className="text-accent underline hover:no-underline">
              the best resolution for Etsy printables guide
            </Link>
            .
          </p>
        </section>

        {/* ListingOutputShowcase — MANDATORY */}
        <section className="mb-16">
          <h2 className="text-2xl md:text-3xl font-bold mb-4">
            One Upload, Correct Pixels at Every Size
          </h2>
          <p className="text-foreground-60 mb-8">
            From a single high-res file, SnapToSize generates every Etsy size at the exact pixel dimensions for a true 300 DPI — no manual math, no guessing whether the DPI tag is honest.
          </p>
          <ListingOutputShowcase artwork="geometric" />
        </section>

        {/* SECTION 6 — How SnapToSize guarantees correct pixels */}
        <section className="mb-16">
          <h2 className="text-2xl md:text-3xl font-bold mb-4">
            How SnapToSize Guarantees Correct Pixels at 300 DPI
          </h2>
          <p className="text-foreground-60 mb-4">
            SnapToSize takes the pixel math off your plate. Upload one high-resolution file and it outputs the exact pixel dimensions at a true 300 DPI for every Etsy size — across all the ratio packs — so you never have to wonder whether a file&apos;s DPI tag matches its real resolution.
          </p>
          <p className="text-foreground-60 mb-4">
            Two safeguards matter here. First, it works <strong className="text-foreground">from a high-res source</strong> — the tool honors the formula, it doesn&apos;t fabricate detail, so the pixels have to exist in your upload first. Second, it <strong className="text-foreground">never crops</strong>: it scales to each size stretch-only, keeping your composition fully intact across every ratio.
          </p>
          <p className="text-foreground-60">
            The result is a set of Etsy-ready files where the DPI tag and the actual pixel count finally agree. If you want to see the manual version of this process first, here&apos;s{" "}
            <Link href="/how-to-resize-images-for-etsy" className="text-accent underline hover:no-underline">
              how to resize images for Etsy
            </Link>{" "}
            — then let SnapToSize do it in one upload. It&apos;s part of the wider{" "}
            <Link href="/etsy-print-sizes" className="text-accent underline hover:no-underline">
              Etsy print sizes
            </Link>{" "}
            system.
          </p>
        </section>

        {/* FinalCTA before FAQ */}
        <div className="mb-16">
          <FinalCTA
            heading="Stop trusting the DPI tag. Ship the right pixels every time."
            stat="up to 70 sizes · true 300 DPI · one upload"
            description="SnapToSize outputs the exact pixel dimensions at a true 300 DPI for every Etsy size from a single high-res upload — no manual math, no honest-DPI guesswork."
            buttonText="Generate Sizes Instantly"
            appUrl={CTA_URL}
          />
        </div>

        {/* FAQ */}
        <section className="mb-16">
          <h2 className="text-2xl md:text-3xl font-bold mb-8">
            Frequently Asked Questions
          </h2>
          <FAQAccordion items={faqs.map((f) => ({ question: f.q, answer: f.a }))} />
        </section>

        {/* Related pages */}
        <RelatedPages currentSlug="dpi-vs-pixel-dimensions" />
      </div>
    </>
  );
}
