"use client";

import { Container } from "@/components/Container";
import { Button } from "@/components/Button";
import posthog from "posthog-js";

export function FinalCTASection() {
  return (
    <section className="py-16">
      <Container>
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Stop resizing manually.
          </h2>
          <p className="text-lg text-foreground-60 mb-8">
            Upload your artwork and get all sizes in 60 seconds. No account needed.
          </p>
          <a
            href="https://app.snaptosize.com"
            target="_blank"
            rel="noopener noreferrer"
            onClick={() => {
              posthog.capture("cta_clicked", {
                source: typeof window !== "undefined" ? window.location.pathname : "",
                cta_type: "hero_final",
                destination: "https://app.snaptosize.com",
              });
            }}
          >
            <Button className="text-base px-8 py-4">Create Your First Print Pack — Free →</Button>
          </a>
          <p className="text-xs text-foreground-40 mt-4 flex items-center justify-center gap-1.5">
            <span className="inline-block w-1.5 h-1.5 rounded-full bg-emerald-400/80 animate-pulse" />
            18,000+ print packs generated by Etsy sellers
          </p>
        </div>
      </Container>
    </section>
  );
}
